apiVersion: v1
kind: Secret
metadata:
  name: borg-credentials
type: Opaque
stringData:
  # Replace with your actual Hetzner Storage Box SSH URL
  BORG_REPO: ssh://u123456@u123456.your-storagebox.de:23/./backups
  # Replace with your strong encryption passphrase
  BORG_PASSPHRASE: "blablaverysecret"
  # Replace with your Healthchecks.io URL for DATA backups
  HEALTHCHECKS_DATA_URL: "https://hc-ping.com/xyz"
  # Replace with your Healthchecks.io URL for CONFIG backups
  HEALTHCHECKS_CONFIG_URL: "https://hc-ping.com/xyz"
---
apiVersion: v1
kind: Secret
metadata:
  name: borg-ssh-secret
type: Opaque
stringData:
  id_rsa: |
    -----BEGIN RSA PRIVATE KEY-----
    xyz
    -----END RSA PRIVATE KEY-----
  known_hosts: |
    1234